site_name: Mapa do Racismo API
site_description: Documentação da API do projeto Mapa do Racismo
site_author: Kelvisduank
repo_url: https://github.com/Kelvisduank/mapa-do-racismo
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
nav:
  - Home: index.md
  - API:
    - Visão Geral: api/visao-geral.md
    - Autenticação: api/autenticacao.md
    - Endpoints:
      - Localizações: api/endpoints/localizacoes.md
      - Tipos de Racismo: api/endpoints/tipos-racismo.md
      - Respostas: api/endpoints/respostas.md
      - Avaliações: api/endpoints/avaliacoes.md
  - Desenvolvimento:
    - Deploy: desenvolvimento/deploy.md
